# Generated by Django 4.2.2 on 2023-07-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category_trendingdeals_dealoftheday'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('Top Wear', 'Top Wear'), ('Bottom Wear', 'Bottom Wear')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], max_length=20),
        ),
    ]
