# Generated by Django 4.2.2 on 2023-07-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_customer_city_remove_customer_locality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_address',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
