# Generated by Django 4.2.2 on 2023-07-23 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_delivery_address_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.delivery_address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
