# Generated by Django 4.2.2 on 2023-07-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_orderplaced_address_orderplaced_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
