# Generated by Django 3.2.20 on 2023-08-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='amount',
            field=models.FloatField(),
        ),
    ]
